name: Update Metadata
on:
  pull_request_target:
    types: [closed]

jobs:
  update-metadata:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Get PR Author
        id: pr_author
        run: |
          author=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
            | jq -r '.user.login')
          echo "author=$author" >> $GITHUB_OUTPUT

      - name: Extract Phone Version
        id: extract_version
        run: |
          version=$(grep -oP 'phone_version=\K.*' version.txt)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Update Metadata
        run: |
          cat <<EOF > metadata.json
          {
            "phone_version": "${{ steps.extract_version.outputs.version }}",
            "last_updated": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "updated_by": "${{ steps.pr_author.outputs.author }}",
            "commit_hash": "${{ github.sha }}"
          }
          EOF

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add metadata.json
          git commit -m "Auto-update metadata for ${{ steps.extract_version.outputs.version }} [skip ci]"
          git push
